FROM debian:stable-slim

RUN apt-get update && \
    apt-get install -y ca-certificates chromium && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY dist/discover-backend /app/discover-backend
COPY .env /app/.env
EXPOSE 4242

CMD [ "./discover-backend" ]

