// Alcance Templates Feature Module
export {
  default as alcanceTemplatesReducer,
  // Thunks
  fetchAlcanceTemplates,
  fetchActiveAlcanceTemplates,
  fetchAlcanceTemplateStats,
  fetchAlcanceTemplateById,
  createAlcanceTemplate,
  updateAlcanceTemplate,
  toggleAlcanceTemplate,
  deleteAlcanceTemplate,
  initializeAlcanceTemplates,
  // Actions
  setFilters,
  clearFilters,
  setPage,
  setPageSize,
  clearSelectedTemplate,
  clearError,
  clearOperationState,
  // Selectors
  selectAllAlcanceTemplates,
  selectAlcanceTemplatesLoading,
  selectAlcanceTemplatesError,
  selectActiveAlcanceTemplates,
  selectActiveAlcanceTemplatesLoading,
  selectSelectedAlcanceTemplate,
  selectSelectedAlcanceTemplateLoading,
  selectSelectedAlcanceTemplateError,
  selectAlcanceTemplateStats,
  selectAlcanceTemplateStatsLoading,
  selectAlcanceTemplateFilters,
  selectAlcanceTemplatePagination,
  selectAlcanceTemplateOperationLoading,
  selectAlcanceTemplateOperationError,
  selectAlcanceTemplateOperationSuccess,
  selectFilteredAlcanceTemplates,
  selectPaginatedAlcanceTemplates,
} from './alcanceTemplatesSlice';